name: Build and Publish
on:
  release:
    types:
      - created

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: ['linux', 'freebsd']
        goarch: ['amd64']
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.16
      - run: mkdir -p build
      - run: GOOS=${{matrix.goos}} GOARCH=${{matrix.goarch}} go build -ldflags "-X main.version=${{ github.event.release.tag_name }}" -o build/webdav_${{matrix.goos}}_${{matrix.goarch}} ./cmd/simple-webdav/
      - run: chmod +x build/webdav_${{matrix.goos}}_${{matrix.goarch}}
      - uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: build/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
